name: Auto Merge Owner PRs

on:
  pull_request_target:
    types:
      - opened
      - synchronized
      - reopened
      - ready_for_review

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Auto Merge if PR author is allowed
        if: ${{ contains(fromJson('["cmihk", "dishao123"]'), github.actor) }}
        run: |
          echo "PR来自指定用户，执行自动合并..."
          gh pr merge --auto --squash "${{ github.event.pull_request.html_url }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
